name: Ruby

on:
  push:
    paths-ignore:
      - "vscode/**"
  pull_request:
    paths-ignore:
      - "vscode/**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        ruby-version: [2.7, 3.0, 3.1, head]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Run the test suite
      run: |
        bundle exec rake TESTOPT=-v

  truffleruby:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: truffleruby
        bundler-cache: true
    - run: bundle exec typeprof --version
